root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server/main.go" 
bin = "tmp/main"
full_bin = ""
args = []
env = []
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_ext = []
follow_symlink = false
stop_on_error = true
log = "air_errors.log"

[run]
cmd = "./tmp/main"
