name: Lint Frontend

on:
  push:
    branches:
      - 'fix*' 
      - 'feat*' 
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.gitignore'
      - 'Makefile'

  pull_request:
    types: [opened, synchronize, reopened] 
    paths:
      - 'frontend/**'
      - 'docker-compose.yml'
      - '.gitignore'
      - 'Makefile'
      
jobs:
  biome-lint:
    name: Biome Lint (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.4.0' 
          cache: 'npm' 
          cache-dependency-path: frontend/package-lock.json

      - name: Install Frontend Dependencies
        run: cd frontend/ && npm ci 

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2 
        with:
          version: latest
          working-directory: frontend/

      - name: Run Biome CI
        run: cd frontend/ && biome ci . 


